# Application numérique des tests

## Création de deux jeux de données

### Simuler un processus de Poisson homogène

```{r}
simulPPh1 <- function(lambda,T_max,fixed_n=-1)
{
  if (fixed_n==-1) fixed_n= rpois(1, lambda*T_max)
  uniformes <- runif(fixed_n, min = 0, max = T_max)
  temps_arrive = sort(uniformes)

  return(temps_arrive)
}
```

```{r}
plot.PP<- function(PP)
{
  # plot the counting process (with jumps of size 1 (starting at point (0,0))):
  plot(c(0,PP),0:length(PP),type="s",xlab="time t",ylab="number of events by time t")
  # add the arrival times on the horizontal axis: 
  points(PP,0*PP,type="p",pch=16)
  # link arrival times with the counts:
  lines(PP,0:(length(PP)-1),type="h",lty=2)
}
```

```{r}
# Simulation and plot of a homogeneous Poisson process:
PPh1 = simulPPh1(2,10)
plot.PP(PPh1)
```

### Simuler un processus de Poisson inhomogène avec un $\lambda$ croissant

```{r}
simulPPi = function(lambda_fct,T_max,M,fixed_n=-1)
{
  PPh = simulPPh1(M,T_max,fixed_n)
  n = length(PPh)
  unif = runif(n,0,M)
  val_fct_lamb = lambda_fct(PPh)
  to_return = sort(PPh[unif < val_fct_lamb])
  return(to_return)
}
```

```{r}
simulPPi_asarticle = function(lambda_fct,lambda_inv,T_max,n)
{
  unif = sort(runif(n,0,lambda_fct(T_max)))
  to_return = lambda_inv(unif)
  return(to_return)
}
```

```{r}
T_max=10
lambda_fct1 <- function(t){return(t)}
lambda_fct1_prim <- function(t){return(0.5*t^2)}
lambda_fct1_inv <- function(t){return(sqrt(t*2))}

M1=2*T_max
PPi1 = simulPPi(lambda_fct1,T_max,M1)
print(PPi1)
# plot:
par(mfrow=c(1,2))
curve(lambda_fct1,from=0,to=T_max,n=1000)
plot.PP(PPi1)
simulPPi_asarticle(lambda_fct1_prim,lambda_fct1_inv,T_max,10)
```

## Test 
### Laplace

```{r}
laplace_stat <- function(arrival_times, T_max) {
  n <- length(arrival_times)
  Y <- sum(arrival_times/T_max) - (n / 2)
  Z <- Y / (sqrt(n / 12))
  return(Z)
}

laplace_test <- function(arrival_times, T_max,alpha){
  X = laplace_stat(arrival_times, T_max)
  pval = 1 - pnorm(X)
  rejete_h0 = (pval < alpha)
  to_return = c(X,pval,rejete_h0)
  return(to_return)
}
```

```{r}
set.seed(18) 
T_max = 10
alpha = 0.05
```

```{r}
PPh1 = simulPPh1(2,T_max)

res = laplace_test(PPh1,T_max,alpha)
print(paste("Rejet de H0 :",res[3]))
print(paste("Stat de test :",res[1]))
print(paste("pvaleur :",res[2]))
```

```{r}
lambda_fct1 <- function(t){return(0.2*t)}

M1=0.2*T_max
PPi1 = simulPPi(lambda_fct1,T_max,M1)

res = laplace_test(PPi1,T_max,alpha)
print(paste("Rejet de H0 :",res[3]))
print(paste("Stat de test :",res[1]))
print(paste("pvaleur :",res[2]))
```
## power
```{r}
calculate_power <- function(test,n_sim, T_max, borne_sup,lambda_func, n =-1, alpha = 0.05) {
  rejections <- 0
  ntot = 0
  for (i in 1:n_sim) {
    PPi1 = simulPPi(lambda_func,T_max,borne_sup,n) 
    Z <- test(PPi1, T_max,alpha)
    if (!is.nan(Z[3]) && !is.na(Z[3])){
      if (Z[3]) {
        rejections <- rejections + 1
      }
      }
  }
  return(rejections / n_sim)
}

calculate_power_asarticle <- function(test,n_sim, T_max, lambda_func,lambda_inv, n, alpha = 0.05) {
  rejections <- 0
  ntot = 0
  for (i in 1:n_sim) {
    PPi1 = simulPPi_asarticle(lambda_func,lambda_inv,T_max,n)
    Z <- test(PPi1, T_max,alpha)
    if (i==1){
      print(PPi1)
    }
    if (!is.nan(Z[3]) && !is.na(Z[3])){
      if (Z[3]) {
        rejections <- rejections + 1
      }
      }
  }
  return(rejections / n_sim)
}
```

```{r}
T_max =10
n_sim=1000
lambda_fct1 <- function(t){return(t+1)}
M1=exp(T_max)

power = calculate_power(laplace_test,n_sim, T_max, M1,lambda_fct1)
power

```

```{r}
weibull_stat <- function(arrival_times, T_max) {
  Z <- 2*sum(log(T_max/arrival_times))
  return(Z)
}

weibull_test <- function(arrival_times, T_max,alpha){
  Zobs = weibull_stat(arrival_times, T_max)
  n=length(arrival_times)
  pval = pchisq(Zobs, df = 2 * n)
  rejete_h0 = (pval < alpha)
  to_return = c(Zobs,pval,rejete_h0)
  return(to_return)
}
```

```{r}
lambda_weibull <- function(theta,Beta,t){
  return ((Beta / theta) * (t / theta)^(Beta - 1))
}
```

```{r}
theta=1
# Définir les valeurs de t
t_values <- seq(0.01, 5, length.out = 500)  # t commence à 0.01 pour éviter t=0 (division par 0)

# Calculer lambda pour Beta = 1 et Beta = 2
lambda_beta1 <- lambda_weibull(theta, Beta = 1, t_values)
lambda_beta2 <- lambda_weibull(theta, Beta = 2, t_values)

# Convertir en data frame pour ggplot
df <- data.frame(
  t = t_values,
  Beta1 = lambda_beta1,
  Beta2 = lambda_beta2
)

# Passer au format long pour ggplot
df_long <- tidyr::pivot_longer(df, cols = c("Beta1", "Beta2"), 
                               names_to = "Beta", 
                               values_to = "Lambda")

# Tracer avec ggplot
library(ggplot2)
ggplot(df_long, aes(x = t, y = Lambda, color = Beta)) +
  geom_line(size = 1.2) +
  labs(title = "Weibull Hazard Function",
       x = "t",
       y = expression(lambda[Weibull](t)),
       color = expression(beta)) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"),
                     labels = c(expression(beta == 1), expression(beta == 2)))
```

```{r}
T_max = 10
alpha = 0.05
theta = 1
```

```{r}
lambda_fct1 <- function(t){return(lambda_weibull(theta,1,t))}

M1=lambda_weibull(theta,1,T_max)
PPi1 = simulPPi(lambda_fct1,T_max,M1)

res = weibull_test(PPi1,T_max,alpha)
print(paste("Rejet de H0 :",res[3]))
print(paste("Stat de test :",res[1]))
print(paste("pvaleur :",res[2]))
```

```{r}
b=1.5
lambda_fct1 <- function(t){return(lambda_weibull(theta,b,t))}

M1=lambda_weibull(theta,b,T_max)
PPi1 = simulPPi(lambda_fct1,T_max,M1)

res = weibull_test(PPi1,T_max,alpha)
print(paste("Rejet de H0 :",res[3]))
print(paste("Stat de test :",res[1]))
print(paste("pvaleur :",res[2]))
```

```{r}
coef_list = c(0.01,0.1,0.2,0.3,0.4,0.5,0.6,1,2)
T_max =10
n_sim=1000

powers_laplace = c()
powers_weibull = c()

for (coeff in coef_list) {
  lambda_fct <- function(t){return(lambda_weibull(sqrt(2 / coeff),2,t))} # équivalent à lambda(t) = coeff * t
  M=lambda_fct(T_max)
  powers_laplace[length(powers_laplace) + 1] <- calculate_power(laplace_test,n_sim, T_max, M, lambda_fct)
  powers_weibull[length(powers_weibull) + 1] <- calculate_power(weibull_test,n_sim, T_max, M, lambda_fct)
}
library(ggplot2)

# Convertir en data frame
df <- data.frame(x = coef_list, Laplace = powers_laplace,Weibull = powers_weibull)
df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                               names_to = "Distribution", 
                               values_to = "Power")

# Créer le graphique
ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Power for a Linear Lambda",
       x = "Linearity Coefficients",
       y = "Power") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
theme_minimal()
```

```{r}
coef_list = c(0.01,0.02,0.03,0.04,0.05,0.1,0.2,0.3,0.5)
T_max =10
n_sim=1000

powers_laplace = c()
powers_weibull = c()

for (coeff in coef_list) {
  lambda_fct <- function(t){return(lambda_weibull((3 / coeff)^(1 / 3),3,t))} # équivalent à lambda(t) = coeff * t²
  M=lambda_fct(T_max)
  powers_laplace[length(powers_laplace) + 1] <- calculate_power(laplace_test,n_sim, T_max, M, lambda_fct)
  powers_weibull[length(powers_weibull) + 1] <- calculate_power(weibull_test,n_sim, T_max, M, lambda_fct)
}

# Convertir en data frame
df <- data.frame(x = coef_list, Laplace = powers_laplace,Weibull = powers_weibull)
df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                               names_to = "Distribution", 
                               values_to = "Power")

# Créer le graphique
ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Power for a t squared lambda",
       x = "Coefficients of the t squared",
       y = "Power") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
theme_minimal()
```

```{r}
library(ggplot2)
beta_list = c(1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0)
T_max =10
n_sim=10000

powers_laplace = c()
powers_weibull = c()

for (b in beta_list) {
  lambda_fct <- function(t){return(lambda_weibull(1,b,t))}
  M=lambda_fct(T_max)
  powers_laplace[length(powers_laplace) + 1] <- calculate_power(laplace_test,n_sim, T_max, M, lambda_fct)
  powers_weibull[length(powers_weibull) + 1] <- calculate_power(weibull_test,n_sim, T_max, M, lambda_fct)
}

# Convertir en data frame
df <- data.frame(x = beta_list, Laplace = powers_laplace,Weibull = powers_weibull)
df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                               names_to = "Distribution", 
                               values_to = "Power")

# Créer le graphique
ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Power as function of beta",
       x = "Beta",
       y = "Power") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
```




```{r}
coef_list = c(1,2,3,5,10,7,8,15)
T_max =10
n_sim=1000

powers_laplace = c()
powers_weibull = c()

for (theta in coef_list) {
  lambda_fct <- function(t){return(lambda_weibull(theta,2,t))} # équivalent à lambda(t) = coeff * t
  M=lambda_fct(T_max)
  powers_laplace[length(powers_laplace) + 1] <- calculate_power(laplace_test,n_sim, T_max, M, lambda_fct)
  powers_weibull[length(powers_weibull) + 1] <- calculate_power(weibull_test,n_sim, T_max, M, lambda_fct)
}

# Convertir en data frame
df <- data.frame(x = coef_list, Laplace = powers_laplace,Weibull = powers_weibull)
df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                               names_to = "Distribution", 
                               values_to = "Power")

# Créer le graphique
ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Power as function of theta",
       x = "theta",
       y = "Power") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
theme_minimal()
```
# on fait les trucs de l'article
## avec nos fctions

```{r}
beta_list = c(1.0, 2.0, 4.0)
n_list = c(10, 20, 40)
T_max = 1
n_sim = 5000

for (b in beta_list) {
  powers_laplace = c()
  powers_weibull = c()
  
  for (n in n_list) {
    lambda_fct <- function(t) {
      return(lambda_weibull(1, b, t))  # équivalent à lambda(t) = coeff * t
    }
    M = lambda_fct(T_max)
    powers_laplace[length(powers_laplace) + 1] <- calculate_power(laplace_test, n_sim, T_max, M, lambda_fct, n)
    powers_weibull[length(powers_weibull) + 1] <- calculate_power(weibull_test, n_sim, T_max, M, lambda_fct, n)
  }
  
  # Convertir en data frame
  df <- data.frame(x = n_list, Laplace = powers_laplace, Weibull = powers_weibull)
  df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                                 names_to = "Distribution", 
                                 values_to = "Power")
  
  # Créer le graphique
  plot <- ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
    geom_point(size = 3) +
    geom_line() +
    labs(title = paste("Power for a Linear Lambda (Beta =", b, ")"),
         x = "Sample Size (n)",
         y = "Power") +
    theme_minimal() +
    scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
  
  # Afficher le graphique
  print(plot)
}



```

```{r}
t_list = c(1.0, 2.0, 4.0)
n_list = c(10, 20, 40)
n_sim = 5000

for (T_max in t_list) {
  powers_laplace = c()
  powers_weibull = c()
  
  for (n in n_list) {
    lambda_fct <- function(t) {
      return(exp(t))  # équivalent à lambda(t) = coeff * t
    }
    M = lambda_fct(T_max)
    powers_laplace[length(powers_laplace) + 1] <- calculate_power(laplace_test, n_sim, T_max, M, lambda_fct, n)
    powers_weibull[length(powers_weibull) + 1] <- calculate_power(weibull_test, n_sim, T_max, M, lambda_fct, n)
  }
  
  # Convertir en data frame
  df <- data.frame(x = n_list, Laplace = powers_laplace, Weibull = powers_weibull)
  df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                                 names_to = "Distribution", 
                                 values_to = "Power")
  
  # Créer le graphique
  plot <- ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
    geom_point(size = 3) +
    geom_line() +
    labs(title = paste("Power for an exponential Lambda (T_max =", T_max, ")"),
         x = "Sample Size (n)",
         y = "Power") +
    theme_minimal() +
    scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
  
  # Afficher le graphique
  print(plot)
}



```

```{r}
t_list = c(10, 15, 25)
n_list = c(10, 20, 40)
n_sim = 5000

for (T_max in t_list) {
  powers_laplace = c()
  powers_weibull = c()
  
  for (n in n_list) {
    lambda_fct <- function(t) {
      return(log(1+t))  # équivalent à lambda(t) = coeff * t
    }
    M = lambda_fct(T_max)
    powers_laplace[length(powers_laplace) + 1] <- calculate_power(laplace_test, n_sim, T_max, M, lambda_fct, n)
    powers_weibull[length(powers_weibull) + 1] <- calculate_power(weibull_test, n_sim, T_max, M, lambda_fct, n)
  }
  
  # Convertir en data frame
  df <- data.frame(x = n_list, Laplace = powers_laplace, Weibull = powers_weibull)
  df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                                 names_to = "Distribution", 
                                 values_to = "Power")
  
  # Créer le graphique
  plot <- ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
    geom_point(size = 3) +
    geom_line() +
    labs(title = paste("Power for an log Lambda (T_max =", T_max, ")"),
         x = "Sample Size (n)",
         y = "Power") +
    theme_minimal() +
    scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
  
  # Afficher le graphique
  print(plot)
}
```

```{r}
to_list = c(1/3, 1/2, 2/3)
n_list = c(10, 20, 40)
n_sim = 1000
T_max=1

for (to in to_list) {
  powers_laplace = c()
  powers_weibull = c()
  
  for (n in n_list) {
    lambda_fct <- function(t) {
      c <- ifelse(t > to, 2, 1)
      return(c)
    }
    M = lambda_fct(T_max)
    powers_laplace[length(powers_laplace) + 1] <- calculate_power(laplace_test, n_sim, T_max, M, lambda_fct, n)
    powers_weibull[length(powers_weibull) + 1] <- calculate_power(weibull_test, n_sim, T_max, M, lambda_fct, n)
  }
  
  # Convertir en data frame
  df <- data.frame(x = n_list, Laplace = powers_laplace, Weibull = powers_weibull)
  df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                                 names_to = "Distribution", 
                                 values_to = "Power")
  
  # Créer le graphique
  plot <- ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
    geom_point(size = 3) +
    geom_line() +
    labs(title = paste("Power for an step function intensity (Tho =", to, ")"),
         x = "Sample Size (n)",
         y = "Power") +
    theme_minimal() +
    scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
  
  # Afficher le graphique
  print(plot)
}
```


## avec leurs fctions

```{r}
library(ggplot2)
beta_list = c(1.0, 2.0, 4.0)
n_list = c(10, 20, 40)
T_max = 1
n_sim = 5000

for (b in beta_list) {
  powers_laplace = c()
  powers_weibull = c()
  
  for (n in n_list) {
    lambda_func <- function(t) {
      return(t^b) 
    }
    lambda_inv <- function(y){
      return(y^(1/b))
    }
    powers_laplace[length(powers_laplace) + 1] <- calculate_power_asarticle(laplace_test, n_sim, T_max,lambda_func,lambda_inv, n)
    powers_weibull[length(powers_weibull) + 1] <- calculate_power_asarticle(weibull_test, n_sim, T_max, lambda_func,lambda_inv, n)
  }
  
  # Convertir en data frame
  df <- data.frame(x = n_list, Laplace = powers_laplace, Weibull = powers_weibull)
  df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                                 names_to = "Distribution", 
                                 values_to = "Power")
  
  # Créer le graphique
  plot <- ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
    geom_point(size = 3) +
    geom_line() +
    labs(title = paste("Power for a Linear Lambda (Beta =", b, ")"),
         x = "Sample Size (n)",
         y = "Power") +
    theme_minimal() +
    scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
  
  # Afficher le graphique
  print(plot)
}

```


```{r}
t_list = c(1.0, 2.0, 4.0)
n_list = c(10, 20, 40)
n_sim = 5000

for (T_max in t_list) {
  powers_laplace = c()
  powers_weibull = c()
  
  for (n in n_list) {
    lambda_func <- function(t) {
      return(exp(t)-1) 
    }
    lambda_inv <- function(y){
      return(log(y+1))
    }
    powers_laplace[length(powers_laplace) + 1] <- calculate_power_asarticle(laplace_test, n_sim, T_max,lambda_func,lambda_inv, n)
    powers_weibull[length(powers_weibull) + 1] <- calculate_power_asarticle(weibull_test, n_sim, T_max, lambda_func,lambda_inv, n)
  }
  
  # Convertir en data frame
  df <- data.frame(x = n_list, Laplace = powers_laplace, Weibull = powers_weibull)
  df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                                 names_to = "Distribution", 
                                 values_to = "Power")
  
  # Créer le graphique
  plot <- ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
    geom_point(size = 3) +
    geom_line() +
    labs(title = paste("Power for an exponential Lambda (T_max =", T_max, ")"),
         x = "Sample Size (n)",
         y = "Power") +
    theme_minimal() +
    scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
  
  # Afficher le graphique
  print(plot)
}
```


```{r}
t_list = c(10, 15, 25)
n_list = c(10, 20, 40)
n_sim = 5000

for (T_max in t_list) {
  powers_laplace = c()
  powers_weibull = c()
  
  for (n in n_list) {
    lambda_func <- function(t) {
      return((1 + t) * log(1 + t) - t) 
    }
    
    lambda_inv <- function(y) {
        # Fonction d'inversion pour un scalaire
        inverse_scalar <- function(single_y) {
          if (lambda_func(0) > single_y || lambda_func(100) < single_y) {
            stop("The function does not change sign in the interval [0, 100]")
          }
          result <- uniroot(function(t) lambda_func(t) - single_y, lower = 0, upper = 100)
          return(result$root)
        }
        # Appliquer à chaque élément de y si y est un vecteur
        return(sapply(y, inverse_scalar))
      }
    
    
    powers_laplace[length(powers_laplace) + 1] <- calculate_power_asarticle(laplace_test, n_sim, T_max,lambda_func,lambda_inv, n)
    powers_weibull[length(powers_weibull) + 1] <- calculate_power_asarticle(weibull_test, n_sim, T_max, lambda_func,lambda_inv, n)
  }
  
  # Convertir en data frame
  df <- data.frame(x = n_list, Laplace = powers_laplace, Weibull = powers_weibull)
  df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                                 names_to = "Distribution", 
                                 values_to = "Power")
  
  # Créer le graphique
  plot <- ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
    geom_point(size = 3) +
    geom_line() +
    labs(title = paste("Power for an log Lambda (T_max =", T_max, ")"),
         x = "Sample Size (n)",
         y = "Power") +
    theme_minimal() +
    scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
  
  # Afficher le graphique
  print(plot)
}
```

```{r}
to_list = c(1/3, 1/2, 2/3)
n_list = c(10, 20, 40)
n_sim = 1000
T_max=1

for (to in to_list) {
  powers_laplace = c()
  powers_weibull = c()
  
  for (n in n_list) {

    lambda_func <- function(t) {
      return(ifelse(t > to, 2*t - to, t)) 
    }
    lambda_inv <- function(y){
      return(ifelse(y > to,(y + to)/2, y))
    }
    powers_laplace[length(powers_laplace) + 1] <- calculate_power_asarticle(laplace_test, n_sim, T_max,lambda_func,lambda_inv, n)
    powers_weibull[length(powers_weibull) + 1] <- calculate_power_asarticle(weibull_test, n_sim, T_max, lambda_func,lambda_inv, n)
  }
  
  # Convertir en data frame
  df <- data.frame(x = n_list, Laplace = powers_laplace, Weibull = powers_weibull)
  df_long <- tidyr::pivot_longer(df, cols = c("Laplace", "Weibull"), 
                                 names_to = "Distribution", 
                                 values_to = "Power")
  
  # Créer le graphique
  plot <- ggplot(df_long, aes(x = x, y = Power, color = Distribution, group = Distribution)) +
    geom_point(size = 3) +
    geom_line() +
    labs(title = paste("Power for an step function intensity (Tho =", to, ")"),
         x = "Sample Size (n)",
         y = "Power") +
    theme_minimal() +
    scale_color_manual(values = c("blue", "red"))  # Personnaliser les couleurs
  
  # Afficher le graphique
  print(plot)
}
```